### ISSUE TITLE
errors while connecting to nvdaremote server

### ISSUE THREAD

**Issue by dave090679** [NVDARemote/NVDARemote#128]
hi all, 

whenever I use nvdaremote 2.0, nvda writes an error to the log file. 

The "nameerror" occurs every time I connect to nvdaremote.com to share my machine to be accessed by other clients. 

I notice this in Windows 7 x64 with no speech synth set. I also have a braillex Trio connected via usb. 
thanks in advance for fixing

Dave
-----------------------------------------
INFO - __main__ (19:01:28):
Starting NVDA
INFO - core.main (19:01:29):
Config dir: C:\Users\tescht\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (19:01:29):
Loading config: C:\Users\tescht\AppData\Roaming\nvda\nvda.ini
INFO - core.main (19:01:29):
NVDA version master-13880,aabbbd75
INFO - core.main (19:01:29):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (19:01:29):
Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
INFO - core.main (19:01:29):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (19:01:29):
Loaded synthDriver silence
INFO - core.main (19:01:29):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (19:01:29):
Using liblouis version 3.0.0
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectBrxCom (19:01:29):
Found Braille Display connected via BRXCom
INFO - braille.BrailleHandler.setDisplayByName (19:01:29):
Loaded braille display driver papenmeier, current display has 40 cells.
INFO - brailleInput.initialize (19:01:29):
Braille input initialized
WARNING - core.main (19:01:29):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (19:01:29):
UIAutomation: IUIAutomation
INFO - core.main (19:01:31):
NVDA initialized
INFO - external:globalPlugins.remoteClient.GlobalPlugin.on_connected_as_slave (19:01:32):
Control connector connected
ERROR - unhandled exception (19:01:33):
Traceback (most recent call last):
  File "wx\_core.pyc", line 16766, in <lambda>
  File "C:\Users\tescht\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 345, in on_connected_as_slave
NameError: global name 'write_connection_to_config' is not defined
INFO - external:globalPlugins.remoteClient.GlobalPlugin.on_connected_as_slave (22:59:17):
Control connector connected
ERROR - unhandled exception (22:59:17):
Traceback (most recent call last):
  File "wx\_core.pyc", line 16766, in <lambda>
  File "C:\Users\tescht\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 345, in on_connected_as_slave
NameError: global name 'write_connection_to_config' is not defined
INFO - config.ConfigManager.save (03:20:35):
Base configuration saved
INFO - core.onEndSession (03:20:36):
Windows session ending

**Comment by leonardder** [comment]
Are you able to build NVDA Remote from source and see whether this problem is still there?

**Comment by leonardder** [comment]
This issue is fixed in master, so I vote for closing this
