### ISSUE TITLE
controller code availability

### ISSUE THREAD

**Issue by vortex1024** [NVDARemote/NVDARemote#14]
I'm not sure this is the proper place to post this, but here goes:
If I understand correctly, nvdaRemote.com also acts  as a public controller to intermediate connections between pc's which are behind NAT.
Is this controller code public? I wasn't able to find it. Can it run on Linux? I thought of making a new public controller in Europe, since nvdaRemote.com, in the US, has a really big lag for us overseas.
Thanks.

**Comment by Simon818** [comment]
I've been wondering this as well, and actually came here to ask about the same thing. Some of the server code is in NVDA itself, but I don't know if it supports multiple slave connections or not, and that would have to be separated and called from another python script. I would definitely host secondary servers in a few far away places if this were made public, and probably one at home for myself as well. I suspect there's a carefully thought out reason why the server code is not yet public though, even if it's as simple as bug fixes and testing. Certainly any companies using NVDA remote would probably want to self host as well, so I doubt it'll be kept private forever.

**Comment by schulle4u** [comment]
As it seems the server code provided in the addon is only able to host a local server when the same machine that runs the server is being controlled. If I try to relay other connections over this server, I'm running into a Connected/disconnected loop until I close the connection.
If there's indeed a separate control server for this purpose, I hope it will be released too. Even if I don't think that no-one responsible for the nvdaremote.com server will ever abuse the transfered data, the ability to self-host the control server would provide more privacy for those who need it.

**Comment by KevanGP** [comment]
The thing that gets me is that I'm not sure how secure the keys are, I think it needs another layer of security.
Maybe have both computer ID and password?

I mean, if someone hacks into the server and/or guesses your key because it's too easy, you're out of luck, they can do just about anything to your computer. Many people probably will use the server at NVDARemote.com, and the boxes for the keys in the addon aren't protected text or anything.

**Comment by pzajda** [comment]
Hi,

On http://www.nvra.me/ there is a list of non-official servers, and a link to download sources on Github : https://github.com/Technow-es/NVDARemoteServer
But the code doesn't seem to be official... An official one would be more than a good thing.

**Comment by leonardder** [comment]
@ctoth, could you tell anything about this?

**Comment by jcsteh** [comment]
I guess this can be closed now that https://github.com/NVDARemote/remote-server is a thing?

**Comment by ctoth** [comment]
Yups, thanks. See https://github.com/nvdaremote/remote-server
