### ISSUE TITLE
sighted users cant help us using nvda remote.

### ISSUE THREAD

**Issue by zahra21** [NVDARemote/NVDARemote#142]
hello nvda remote programmers and developers.
thanks extremely for your great work!
i use nvda remote.
but i need help from sighted persons.
nvda remotes only support speech and not graphics, video and also any visual and written on the screen.
when i need help from sighted people, i should use teamviewer and other remote programs.
it needs a more internet bandwidth and not useful for the people whose internet charge is limited.
i appreciate you if you  add support video to also sighted persons can help us and even we can help sighted persons!
thanks extremely for your help, i pray for you and request divine infinite mercy for you.

**Comment by leonardder** [comment]
> i appreciate you if you add support video to also sighted persons can help us and even we can help sighted persons!

The latter will always require NVDA with remote to be running on the sighted person's computer.
Honestly, I'm against this feature. Teamviewer is a perfect alternative for this, and as far as I know, you can bring down its bandwidth usage if you so desire. It is just not the best in accessibility. But there also is an add-on for this.

Any how, sighted assistance is far beyond the scope of NVDA Remote.
