### ISSUE TITLE
Decide which string type to use

### ISSUE THREAD

**Issue by leonardder** [NVDARemote/NVDARemote#156]
NVDA Remote currently uses regular str type strings to communicate. When updating to Python 3, the current code base will automatically send unicode strings, since the string type isn't explicitly defined. I belief it is necessary to choose between one or the other, and my personal preference leans towards Unicode. I wonder whether this has compatibility implications though, e.g. will Python automatically deal with converting this appropriately?

**Comment by bramd** [comment]
I think it would be best to work with unicode strings inside the codebase and convert them to utf-8 explicitly when sending them over a transport.

**Comment by ctoth** [comment]
Completed as part of Python 3 work, thank you!
