### ISSUE TITLE
Braille support is broken with newly supported SuperBraille

### ISSUE THREAD

**Issue by school510587** [NVDARemote/NVDARemote#158]
Hi,

I use NVDARemote in NVDA 2017.3 with newly supported SuperBraille display.
However, I receive the following error messages:

INFO - braille.BrailleHandler.setDisplayByName (23:16:30.640):
Loaded braille display driver superBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (23:17:23.515):
Loaded braille display driver superBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (23:17:47.358):
Loaded braille display driver superBraille, current display has 40 cells.
ERROR - scriptHandler.executeScript (23:18:04.578):
error executing script: <bound method GlobalPlugin.script_sendKeys of <globalPlugins.remoteClient.GlobalPlugin object at 0x0382A1B0>> with gesture 'f11'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "C:\Documents and Settings\user\Application Data\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 382, in script_sendKeys
  File "C:\Documents and Settings\user\Application Data\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 394, in set_receiving_braille
AttributeError: 'NoneType' object has no attribute 'Stop'

P.S. My OS is 32-bit version.
The following line in __init.py produced these errors:

braille.handler._messageCallLater.Stop()

I further read braille.py in NVDA, and I find it always checks _messageCallLater before calling Stop(). That is,

if self._messageCallLater:
    self._messageCallLater.Stop()
    self._messageCallLater = None

Therefore, please check _messageCallLater before calling Stop(). Thanks!

**Comment by leonardder** [comment]
Could you create a pr yourself? If not, I'm happy to do this.

**Comment by school510587** [comment]
@leonardder, I have created PR #159.
