### ISSUE TITLE
How to update the bulgarian translation of the NVDA Remote add-on

### ISSUE THREAD

**Issue by k-kolev1985** [NVDARemote/NVDARemote#165]
Hello all,

I'm using version 2.1 of the NVDA Remote add-on. I've noticed that there are some strings which are not translated to bulgarian. I've checked the bulgarian .po file for the add-on (in the add-on's installation directory) and all available strings there are translated. Examples of not translated strings are in the menu of the add-on in the NVDA's "Tools" menu ("Mute remote", "Copy link"), the message that is shown in a dialog after a successful connection, and maybe some others as well, that I haven't noticed. Is this only for the bulgarian translation or for all of them? Can I fix it?

I think the bulgarian documentation is also out of date.

I don't see the NVDA Remote add-on available for translation in the NVDA translations repository. Why?

Thanks much in advance!

**Comment by zstanecic** [comment]
hi kostadin, 
You should checkout the github repo of the addon, firstly forking it

**Comment by k-kolev1985** [comment]
Well, I'm not that familiar with GitHub at this time, so I guess I'll leave it as it is. Maybe if the process becomes more intuitive like it is for the add-ons on the official NVDA add-ons page or if get more familiar with GitHub in the future, I'll do it. But not now...
