### ISSUE TITLE
way, besides f11, to switch between systems

### ISSUE THREAD

**Issue by a-singer** [NVDARemote/NVDARemote#172]
Hello,
I am in need of a method to switch between the local and remote system other than using the f11 key. I can neither change this key in input gestures nor is there a menu option to change system control. Either of these would be helpful.
Thanks

**Comment by alekssamos** [comment]
Key skip mode (NVDA+F2)  doesn't help? Or do you always have to?

**Comment by ctoth** [comment]
This has been implemented in #333
