### ISSUE TITLE
Allow file transfers between machines

### ISSUE THREAD

**Issue by zahyur** [NVDARemote/NVDARemote#20]
Similar to the clipboard transfer functionality (the "Push clipboard" command), one may need to transfer a file to the other machine.
Currently, one should use another program for that purpose, which makes things unnecessary complicated.
I suggest introducing a new command - "Transfer file", which would behaive similar to "Push clipboard", with one additional step - choosing the file to be transfered.
The only one potential problem I see is the bandwidth of the relay server, when one is used. A possible solution is limiting the transfer speed on the relay server itself.

I'm looking forward to hear your thoughts.

**Comment by ctoth** [comment]
This is outside the scope of NVDA Remote. If you wish to transfer files I recommend using an external service such as Dropbox.
