### ISSUE TITLE
Braille is not working properly with nvda 2019.3 and later

### ISSUE THREAD

**Issue by GianGythub** [NVDARemote/NVDARemote#222]
### remote machine, cursour routing do not work at all and it is not possible to use left or right panning to show the remaining text on the display or to move in a text to perform reading.

**Comment by ABuffEr** [comment]
Hi @GianGythub ,
same here, but I found a solution (few minutes ago). Simply add missed imports for vision and baseObject in input.py module, under remote/globalPlugins/remoteClient.
In sources hosted here, @ctoth , I see import for vision, but baseObject is still missing.

**Comment by tech10** [comment]
@GianGythub I have tested #229 by building my own version of the add-on. Braille display support does seem functional, curser routing and panning. I didn't test an older version of the add-on to see if the issues would have existed for me before. Have you tested #229 to see if it will work for you, can this issue be closed?

**Comment by ABuffEr** [comment]
Hi @tech10 ,
@GianGythub contacted me privately some time ago, and I can confirm that he solved integrating changes I put in #229; so, the issue can be closed.

**Comment by ctoth** [comment]
Fixed in #229
