### ISSUE TITLE
Problems connecting and working

### ISSUE THREAD

**Issue by alekssamos** [NVDARemote/NVDARemote#228]
1. Sometimes there is a sound signal about connecting, but the keyboard and speech are not transmitted.
2. Sometimes it only works if you are in help mode, in a document, or in an editor. Moving through elements and Windows is not spoken, but only if you press the NVDA+Tab key combination.
Why does this problem occur and how can I fix it? There were already two people.
I tried different versions Remote and Windows, not help. NVDA installation, administrator rights are available. Mobile Internet connection, 4G / LTE, stable, music and videos in high quality play well.

**Comment by tspivey** [comment]
Go into NVDA's Advanced settings and set Attempt to cancel speech for expired focus events to Default on the remote machine. See if that fixes it.

**Comment by KevGP** [comment]
I'm also having issues with the newest NVDARemote for the newest NVDA. It's just not as stable as it was before.

**Comment by KevGP** [comment]
I did varify TSpivey's suggestion was correct on my remote machine.

**Comment by cary-rowen** [comment]
> Go into NVDA's Advanced settings and set Attempt to cancel speech for expired focus events to Default on the remote machine. See if that fixes it.

It can indeed solve the problem, but this is only a temporary solution. This is not the best solution, because NVDA will set this option to "Yes" by default in the new version.
Hope someone can fix this error.
[Please see the explanation of NVDA issues](https://github.com/nvaccess/nvda/issues/11736)

**Comment by seanbudd** [comment]
Closed via https://github.com/NVDARemote/NVDARemote/pull/237
