### ISSUE TITLE
Update NVDARemote to support cancellable speech

### ISSUE THREAD

**Issue by feerrenrut** [NVDARemote/NVDARemote#230]
NVDA will be making cancellable speech commands available by default in the 2021.1 release of NVDA. This will also be a backwards compatibility breaking release, with an upgrade to Python 3.8. As such NVDA remote will need to be updated in order to be able to continue to work with the latest version of NVDA. A full list of compatibility breaking changes is maintained in the change log for NVDA.

For more information about cancellable speech, please see: https://github.com/nvaccess/nvda/issues/11736
Also related: https://github.com/NVDARemote/NVDARemote/issues/228

**Comment by feerrenrut** [comment]
I think fixing this is as simple as adding Cancellable speech commands to https://github.com/NVDARemote/NVDARemote/blob/master/addon/globalPlugins/remoteClient/session.py#L17

**Comment by cary-rowen** [comment]
Very much hope to be able to update
