### ISSUE TITLE
NVDA 2021.1 compatibility

### ISSUE THREAD

**Issue by Timtam** [NVDARemote/NVDARemote#247]
We're at NVDA 2021.1 beta 2 right now, and the new full release is scheduled to be released soon. Thats the moment where everyone will update to the latest version and NVDA remote will stop working. I don't know what needs to be updated, but I guess its time for an evaluation what and how much needs to be changed in order to maintain compatibility.

**Comment by ctoth** [comment]
@tech10 Thanks. Yups exactly this. NVDARemote will never put out releases for a beta version of NVDA, but I expect we'll have a release out when the actual release of NVDA occurs.
Lots of nice stuff coming in this new version :)

Thanks all for your help getting this done!
