### ISSUE TITLE
Update documentation for version 2.4

### ISSUE THREAD

**Issue by nvdaes** [NVDARemote/NVDARemote#269]
- Reflect version 2.4, not 2.3.
- - Include release notes.
This has been discussed at

https://github.com/nvaccess/addonFiles/pull/118

**Comment by cary-rowen** [comment]
Yes, we should add documentation, version 2.4 has some exciting changes

**Comment by hamidrezaabroshan** [comment]
Yes. we are waiting for update in the docs.

**Comment by cary-rowen** [comment]
@nvdaes 
At present, readme.md has been updated, can this issue be closed?
Thanks

**Comment by nvdaes** [comment]
OK, then let's close it. Thanks.
