### ISSUE TITLE
In NVDA 2021.1, connect dialog focuses OK button first over client radio button

### ISSUE THREAD

**Issue by tech10** [NVDARemote/NVDARemote#275]
Building the addon against 241c0e4 and using it with NVDA 2021.1 presents the following issue. When opening the connect dialog to create a connection with another computer, the OK button is focused first, something that is incongruent with the options dialog, and other dialogs in NVDA itself. It's also counterintuitive, but easily enough worked around by tabbing to the appropriate elements to use. Before this, the first item focused would be the client radio button in the first group, selecting whether or not a client or server is used for the addon's connection.

This may also be present with fa5b6df but I haven't tested this, as my current build as of this issue is the most stable when it comes to connection dropouts, due to the SSL thread safety issue and a lock to work around it.

**Comment by cary-rowen** [comment]
It's just a personal preference, I prefer it to stay on the client radio button.

**Comment by cary-rowen** [comment]
This issue appears to have been resolved, Would you mind looking into it and then consider closing it?

**Comment by tech10** [comment]
This does appear to be resolved.
