### ISSUE TITLE
No control on windows UAC screens

### ISSUE THREAD

**Issue by nktech1135** [NVDARemote/NVDARemote#278]
After following the docs to allow control of UAC screens i still can't control them. When a secure screen pops up i have no control of it remotely. @tspivey i see you made a commit that might fix them, but i can't build the addon from the master branch to test it. the build process errors out because of a missing directory.

**Comment by tech10** [comment]
@nktech1135
Try this build that I made on July 29, not the latest for localizations, but I believe it was for everything else when I built it from the master branch. [Download it here.](https://www.vrnw.org/nvda/remote-2.4.nvda-addon)

See if that works for you, I'm able to use this to control UAC screens perfectly.

**Comment by nktech1135** [comment]
Thanks, that does indeed work.
I don't care about localizations since the systems i work with are all english, so this does fix my issue.
