### ISSUE TITLE
Remote 2.4 is not as stable as 2.3

### ISSUE THREAD

**Issue by hamidrezaabroshan** [NVDARemote/NVDARemote#279]
I'm using nvda 2021.1 with windows 10 enterprize on both computers and one of machines used as server with static ip.
I'm disconnect frequently while I didn't have these problems with 2.3.
Also, in lock screens it goes to a loop and when I press any key it will disconnect and connect back again.
Thanks.

**Comment by hamidrezaabroshan** [comment]
Sometimes, it does not connect at all specially in secure screen.

**Comment by jcsteh** [comment]
This is probably fixed by #274.

**Comment by cary-rowen** [comment]
@hamidrezaabroshan 
According to my test #274 solved this problem, can you confirm?

Thanks

**Comment by ctoth** [comment]
Fixed in #274, thanks @jcsteh
