### ISSUE TITLE
Hide the options dialog (or obscure the remote key) on secure screens

### ISSUE THREAD

**Issue by Simon818** [NVDARemote/NVDARemote#296]
In a hypothetical scenario where (1) my computer is set to autoconnect to a remote server on the logon screen, and (2) someone has physical access to my machine, and (3) that person knows how to use NVDA, they could very easily harvest the remote key just by turning the computer on and opening up the options dialog. They then have permanent access to my system as long as it's logged in. There's not really a defense against this unless I use a separate key in systemConfig. With that in mind, I suggest either hiding the menu option entirely or hiding the remote key in the options dialog. If this doesn't happen, I'll likely just patch it out of existence on my system copy of the addon. Thoughts?

**Comment by tech10** [comment]
This seems like a good idea, though it may be more useful to hide the entire menu for the addon on secure screens.

**Comment by ctoth** [comment]
Pull requests are welcome.

**Comment by cary-rowen** [comment]
@Simon818 
Are you going to open this PR? Should we disable the entire remote menu?
Thanks
