### ISSUE TITLE
nvda remote The IOS version keyboard error

### ISSUE THREAD

**Issue by c469591** [NVDARemote/NVDARemote#297]
Hello!
The IOS version of the given some remote button position is wrong,
For example, /, \; , that is the right of the keyboard area, many key output to the remote control computer is wrong,
It for the user to use Chinese input is very worry, hope can be repaired,
Thank you!

**Comment by tech10** [comment]
What you are referring to is not an official project endorsed by NVDARemote itself, it was created by another individual. Issue [#14](https://github.com/EscolarProgramming/NVDARemotePublic/issues/14) is where this has been recorded.

**Comment by c469591** [comment]
Thank you very much! I have already reply over there!
