### ISSUE TITLE
add  another option to connect dialog for both

### ISSUE THREAD

**Issue by amirmahdifard** [NVDARemote/NVDARemote#308]
currently, we are only limited to controling another computer, or allow our computer to be controled: but for my job since i need to controle another  computer with my current computer and also controle my current computer with the another computer, so everytime i want to do that i must disconnect, change it to the other radio button, and connect again: and also, i beleave that some people are like to controle their both computers at the same time: and adding this feecher won't be annoyingvfor any people: in the connect dialogue, we should have 3 radio options: 1: controle another computer, 2: allow this computer to be controled, and 3: both, controle and be controled: then, people are completely free to use any option: if people wants to select the both option, the 2 person from both side should select the both radio button: once they did and connected, both people will have speech of the other side computer, they both will be able to press f11 key and controle the other computer while the other computer will also be able to controle this computer, and both sides will also be able to use send controle alt delete option too: anyway, everything will be avalable for both connected sides: this feecher is really look good to me, please one of the contributers could impliment this if possible: thanks.

**Comment by tech10** [comment]
I could see where this feature could be useful, though it would introduce a little added complexity that I think might be necessary.

If computer A is controlling computer B, then computer B tries to control computer A, this should be unavailable for them until computer A stops controlling computer B with F11. Or, computer B could have an option in their menu, stop a computer controlling my own, or something like that. Only then could computer B control computer A, should computer A be controlling computer B, which would be remotely terminated at that point.

**Comment by amirmahdifard** [comment]
no, that what i said: if computer a doesn't want to controled by computer b, then they shouldn't use the both option: i see the both option is useful if my friend is controling my laptop, and i'm controling his laptop at the same time: but still, if you want to add an option so that computer x shouldn't be able to controle computer y if computer y is already controling computer x, you can do it, but both should be mean that both should do that at the same time.

**Comment by amirmahdifard** [comment]
for example, with the both option, i want to do something on my friend's computer, while he is also doing something on my laptop

**Comment by amirmahdifard** [comment]
@josephsl @beqabeqa473 @jmdaweb could you please think about it, i beleave you can do this if you are agreed and wanted to

**Comment by tech10** [comment]
I understood your review of the feature you'd like to see. However, if both computer A and computer B use this option for controlling and being controlled, then computer A controls computer B with F11, computer B cannot control computer A when F11 is pressed, since any key press from computer A will go to computer B. In this case, since computer A is still controlling computer B, computer B will attempt to control computer A once they press F11, but computer A will still send all key presses to computer B, who will send them back to computer A, back to computer B, etc. This infinite loop would have to be prevented before it can begin.

My understanding of how the key presses are intercepted by NVDA, is that all remote key presses would also be intercepted. Thus, creating the infinite loop I've presented. I'm not sure how else this could be prevented.

**Comment by amirmahdifard** [comment]
then in that kase, i agree with you that while computer x is controling computer y, computer y shouldn't be able to controle computer x until computer x stopped controling computer y

**Comment by amirmahdifard** [comment]
@ctoth i'm sorry to asking this, but anyone didn't pay any attention to this eccept tek10: is this project is abandened? please at least pay attention to users: i mentioned like 4 people in here, but they don't care.

**Comment by amirmahdifard** [comment]
@tech10 friend, your the only one who paid attention to this, can you please open a pool request for this as how you think you can add this? thanks so much if you reply me.

**Comment by tech10** [comment]
Unfortunately, my Python programming skills are extremely limited, I won't be able to create a PR for this issue, or I might have already started on this. Furthermore, this would require some changes in the protocol, so I'm unsure how the developers might handle this, if they are going to take your request into account.

**Comment by amirmahdifard** [comment]
@tech10 it's so sad, because, i see that you want this feecher but you are limited and you can't do that, and the people who are able ro do this are don't want and don't care about it: it's sad for me that in this modern life, moste of the people are like that.

**Comment by amirmahdifard** [comment]
@tech10 again, thank you for your thumbs up emoji and for your interests: i'll keep this open for a little while more and if stil nothing is going about it, i'll just close it that's what happens when developer doesn't respect user.

**Comment by amirmahdifard** [comment]
@tech10 bro, what do you think? should i keep this issue open, or should i close it? thanks.

**Comment by lbk2907** [comment]
It’s seems there are no any response about this issue.
Personally, it will be grate if this feature is implemented.

**Comment by tech10** [comment]
@amirmahdifard Keep it open, it seems at least one other has expressed interest.

**Comment by lbk2907** [comment]
Another feature that I can think is control 2 computer in the same time. That’s mean user can control computer A and computer B in the same time either in the same or different host and key. User have an option to choose which computer they want to control. That option will be available if user connect to 2 computer in the same time.

**Comment by tech10** [comment]
I could see this being useful as well.

There have been times when I've wanted to connect to more than one computer at once, to monitor one and control another, then switch to a second when I wanted to control it. You'd need another command to switch between which computer you're controlling. CTRL+F11 for instance, then you could use F11 to control the computer or not, as normal.

**Comment by lbk2907** [comment]
I agree with this method. Is more easier though.

**Comment by blindgeek** [comment]
Is this correct that the latest version is still 2.2?

**Comment by lbk2907** [comment]
No. The latest version is 2.5.

**Comment by blindgeek** [comment]
Wow. Where to get that release please? I only see 2.2 when I do git clone.

**Comment by lbk2907** [comment]
https://nvdaremote.com/remote-2.5.nvda-addon

**Comment by blindgeek** [comment]
Appreciate it thanks.

**Comment by lbk2907** [comment]
You’re most welcome.

**Comment by amirmahdifard** [comment]
@tech10 @lbk2907 thank you both: i very liked the suggestion that you gave too, but very sad because there are no action from developers
