### ISSUE TITLE
Question for support braille display for NVDA Remote 

### ISSUE THREAD

**Issue by KihunJang1981** [NVDARemote/NVDARemote#356]
Dear Sir,

I am developer for HIMS Braille Sense.
We try to connect NVDARemote in the HIMS Braille device.
So we sucess to connect the NVDARemote.
And we receveie the display and speak data.
But I do not sucess to send the "braille_input".
I send the "dots" or "space" or "routingIndex."
But it is not work.
How to send the braille_input data?
Thank you.

**Comment by ctoth** [comment]
Is there a reason that you opened another issue... When you already had an open discussion?

**Comment by KihunJang1981** [comment]
I am sorry. I don't process.
