### ISSUE TITLE
NVDARemote needs the ability to set the port number

### ISSUE THREAD

**Issue by ghost** [NVDARemote/NVDARemote#39]
I'm creating this issue because port 6837 doesn't always work for everyone.

I tried to control a home computer from a restricted Wi-Fi network, and it wouldn't connect presumably because the network blocks all ports except the usual ones (80, 443, 8008 etc.).

Even if the addon could allow the changing of port numbers for just direct connections, this would be cool.

**Comment by hamzalatif7** [comment]
agreed the port changing feature would also be good for changing ports especialy when trying to connect to someones computer threw  a restrictiv firewall setup in my case i can't connect to the remote machine  due to the port beeing blocked

**Comment by leonardder** [comment]
I agree on this and would be able to implement, if core devs like @ctoth agree.

**Comment by leonardder** [comment]
This issue can be closed.

**Comment by ctoth** [comment]
Agreed, thank you.
