### ISSUE TITLE
Self-host support on startup?

### ISSUE THREAD

**Issue by KevanGP** [NVDARemote/NVDARemote#40]
Can the addon be easily made to have the ability to use itself as a control server all the time?
Currently this option is only possible if you set it manually, not automatically when the addon starts up. I'm not sure if that would be a security risk, though.

**Comment by leonardder** [comment]
Honestly, I'd also like such a possibility. I think it shouldn't be that difficult to implement

**Comment by KevanGP** [comment]
I have a patch someone made from the 1.03 version that does this,
along with adding some keystrokes from within NVDA to perform actions
like connect, disconnect, say status, etc. So far though these haven't
been put into the new official versions.
I'll get you a Dropbox link that should be up for a while.
https://dl.dropboxusercontent.com/u/19505455/remote-1.03%20-%20all%20blake%27s%20changes.nvda-addon

**Comment by leonardder** [comment]
As far as I know, pull requests have been made for the keystrokes, but 
not for the autostart control server part. I guess the pull request 
method for the separate issues is prefered in case of the developers.

**Comment by KevanGP** [comment]
Now all we have to wait for is the developers to accept the requests,
whenever that will be.

**Comment by leonardder** [comment]
I tried the provided patch, and it spits out an error when you select connect to control server, than leave the host field blank and after thatselect the selfhost option. Furtgermore, it must be considered whether we also want to autoconnect to a selfhosted or another server in client mode, when this is desired.

**Comment by Oliver2213** [comment]
I just released a new version on my fork of the addon.
I opened those pull requests several months ago and haven't heard anything, so I decided to just go ahead with my version.
Take a look at https://github.com/oliver2213/NVDARemote, and you can download my 1.3 release [here](https://github.com/oliver2213/NVDARemote/releases).
