### ISSUE TITLE
Changelog and documentation?

### ISSUE THREAD

**Issue by ghost** [NVDARemote/NVDARemote#41]
I noticed the addon has been updated to 1.1.
Curious what's new in 1.1? I couldn't find a changelog in the addon's files and folders. I did find the documentation which seems to not have been updated since 1.0.
The documentation probably should be in the menu, to make it easier to find for some who don't know where to look?

**Comment by TKavanaugh** [comment]
I would think the way to get the changelog would be to diff from the 1.1 tag back to the 1.0 tag, or do a git log between those two revisions?

**Comment by gregjozk** [comment]
Hi,

first of all, thank you for your good work. I saw, that NR was updated but did not find a updated documentation. Can you provide it please so we can use all great features of addon such is braille support.

regards, Jožef
