### ISSUE TITLE
Remote doesn't work on secure desktop when auto connect is on

### ISSUE THREAD

**Issue by leonardder** [NVDARemote/NVDARemote#51]
NVDA Remote is able to work on the secure desktop whenever you copy de user config to the system config for the secure desktop. However, this seems not the case when you have autoconnect enabled

STR:
1. Go to NVDA Remote options, and enable autoconnect to control server. Enter the prefered host and key, and press ok
2. Save NVDA Settings
3. GO to NVDA general options and choose "use currently saved settings on the logon screen"
4. After copying, restart NVDA. It will connect to the control server
5. Go to the secure desktop
Expected: The remote controller reads the secure desktop
Actual: No secure desktop is read, remote controller is stuck

**Comment by allanwkf** [comment]
Yes, I agree to this issue, hope this issue can be fix soon, quite difficult to control the remote server if there's secure screen appear.

**Comment by pzajda** [comment]
Hi,

I also noticed this issue.
But I also noticed it worked sometimes and I don't see why.

**Comment by ctoth** [comment]
This appears to work, it just takes a while for the remote secure desktop NVDA to start up. Any feedback?

**Comment by leonardder** [comment]
I wonder whether #91 fixes this. Probably not, though.

**Comment by csm120** [comment]
I'm having the same issue. Even when copying the settings I cannot control a machine from a logon screen for example. If someone does something in that screen I'll here that but I cannot take control even when it's connected.
