### ISSUE TITLE
Mute remote speech doesn't apply to browse mode sounds

### ISSUE THREAD

**Issue by leonardder** [NVDARemote/NVDARemote#52]
It seems that, when mute remote speech is enabled, browse mode sounds still come through on the controlling pc. I've not yet been able to test this with progress bars. In any case, this is non-expected behavior to me.

**Comment by ctoth** [comment]
Agree this may be unexpected. We should probably change the name of the option to reflect muting everything if we do change what it does though.
Thoughts on what it should be called? Remote Mute?

**Comment by ctoth** [comment]
I also had remote muting apply to tones sent from the remote machine.
