### ISSUE TITLE
Possible bug in server's handling of incoming client data

### ISSUE THREAD

**Issue by FelixGruetzmacher** [NVDARemote/NVDARemote#56]
In server.py, line 84, we have:
			data = self.buffer + self.socket.recv(8192)
That is, buffer plus newly received bytes go to data.
Then, in lines 91 and 92, we have:
		if '\n' not in data:
			self.buffer += data
That is, if data does not contain newline it is appended to buffer.
So if buffer was not empty, it will end off containing its initial content twice, followed by what was received.
Suggestion: Change line 92 to
			self.buffer = data

**Comment by tspivey** [comment]
Thanks.

I fixed this a while ago in master, commit 749fff58bc1ba30a9e8854d6f2a10744697b4baa.
That exposed another bug, fixed in ad413e2d79a5eb27f19ae81b0d3c071cf51a6e7f.
