### ISSUE TITLE
Improve f11 handling

### ISSUE THREAD

**Issue by tspivey** [NVDARemote/NVDARemote#66]
Currently, f11 is processed from inside the master's keyboard hook.
This is problematic because nothing on the master system can use F11 for anything.

One solution to this would be to add F11 as an NVDA gesture when the master is connected,
then only handle the F11 from inside the keyboard hook to exit. The gesture would need to be unbound when disconnected.
If done this way, we can press f11 on the host by passing it through, and it wouldn't interfere with modifiers+F11.

**Comment by ctoth** [comment]
We should dynamically set the hook to whatever the gesture is set to, so 
it's consistent in and out of remote.

**Comment by tmthywynn8** [comment]
This code breaks the error dialog when connecting to a nonexistent NVDA server.

STR:
  1. Connect to a remote machine as a controller.
  2. Enter another domain other than nvdaremote.com (e.g. google.com). It must not be an NVDA remote server, or at the very least offline.
  3. Enter any nonexistent key and press enter.
  4. Wait a few seconds, and you'll here an error tone if you're not running a main release. In the log, you'll get:
```
ERROR - unhandled exception (hh>:<mm>:<ss>):
Traceback (most recent call last):
  File "wx\_core.pyc", line 16766, in <lambda>
  File "<...>\remoteClient\__init__.py", line 229, in on_slave_connection_failed
  File "<...>\remoteClient\__init__.py", line 220, in disconnect_from_slave
  File "baseObject.pyc", line 179, in removeGestureBinding
KeyError: u'kb:f11'
```

**Comment by tspivey** [comment]
Thanks. I forgot to test this. Fixed.
