### ISSUE TITLE
Support for RDP and Citrix

### ISSUE THREAD

**Issue by leonardder** [NVDARemote/NVDARemote#74]
This is a quite advanced feature, but would close the gap between NVDA and commercial screen readers. If another crowdfunding campaign would start for this, I'd donate for sure.

**Comment by leonardder** [comment]
@BabbageCom now sells this functionality, closing for now.

**Comment by marioloreti** [comment]
Sorry can I have bore information about this functionality? I can't understand the language of the syte you mentioned.
