### ISSUE TITLE
Protocol changes to support braille with multiple masters

### ISSUE THREAD

**Issue by leonardder** [NVDARemote/NVDARemote#93]
For proper braille support implementation (#68) as well as to be future proof, it is desirable to change the server and protocol according to the following:

* The client ID of the sending client should be added to every message server side. This can be done in server.Client.parse, for example. Another but uglyer approach could be that the client itself adds its ID to all messages it sends. This requires that the client knows its own ID. Anyhow, a slave client should be able to know which master client sends a particular message
* The server should keep track of whether a client is connected in slave or master mode. Thus, server.Client should have a type property, which is either 0 (master) or 1 (slave). This will allow the server to reject multiple slaves in one channel, which would lead to very undesirable behaviour. Also, Client.send_to_others can be changed so that information from a slave client will only be send to masters, for example. This way, we won't have the situation that slave clients will end up in session.SlaveSession.masters as it is currently the case.
* There should be some way for the server and clients to see whether their protocols are compatible. The updated server should actively reject outdated clients, and a client shouldn't connect to an outdated server

**Comment by ctoth** [comment]
I made a few minor changes to this -- storing connection type as a string, for instance, but implemented pretty much exactly what you asked for in #105 :)
